Repository neophytz/hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#7 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#8 Create Contributors.md
  Contributors.md
Labels: hacktoberfest2022, hacktoberfest

#41 commit done
  Dino-Game/DinoGame.js
  Dino-Game/assets/block.png
  Dino-Game/assets/cloud.jpg
  Dino-Game/assets/dino.png
  Dino-Game/assets/road.png
  Dino-Game/style.css
  index.html
Labels: hacktoberfest2022, hacktoberfest

#12 Added solution for a JS Program
  Javascript Programs/Fibonacci.js
  Javascript Programs/Linked_list.js
  Javascript Programs/Merge-sort.js
Labels: hacktoberfest2022, hacktoberfest

#40 Made ToDo List using HTML, CSS and Js
  ToDo List/index.html
  ToDo List/script.js
  ToDo List/style.css
Labels: hacktoberfest2022, hacktoberfest

#38 commit done
  reversestring/reverse.js
Labels: hacktoberfest2022, hacktoberfest

#36 commit done
  javascript program/celsiustofahrenheit.js
Labels: hacktoberfest2022, hacktoberfest

#34 Developed simple program to create a flappy bird games
  Games/flappy.cpp
Labels: hacktoberfest2022, hacktoberfest

#31 commit done
  linkedlist/linkedlist.js
Labels: hacktoberfest2022, hacktoberfest

#30 Added Tic-Tac-Toe code using C++
  .vscode/settings.json
  .vscode/tasks.json
  Games/TicTacToe.cpp
  Games/TicTacToe.exe
Labels: hacktoberfest2022, hacktoberfest

#27 Create SieveofEratosthenes.py #5
  Python/SieveofEratosthenes.py
Labels: hacktoberfest2022, hacktoberfest

#26 bubblesort
  bubblesort/bubblesort.js
Labels: hacktoberfest2022, hacktoberfest

#24 countingsort
  countingsort/countingsort.js
Labels: hacktoberfest2022, hacktoberfest

#21 mergesort
  js/mergesort.js
Labels: hacktoberfest2022, hacktoberfest

#20 Create Readme.md
  Readme.md
Labels: hacktoberfest2022, hacktoberfest

#19 Added Readme FIle
  Readme.md
Labels: hacktoberfest2022, hacktoberfest

#18 Updated Contributors.md
  Contributors.md
Labels: hacktoberfest2022, hacktoberfest

#15 Fixed a issue of creating simple animated text
  Frontend-PRojects/Animated Text/index.html
  Frontend-PRojects/Animated Text/style.css
  Frontend-PRojects/Calculator/index.html
  Frontend-PRojects/Calculator/script.js
  Frontend-PRojects/Calculator/style.css
  Frontend-PRojects/Show-Hide-Password/index.html
  Frontend-PRojects/Show-Hide-Password/script.js
  Frontend-PRojects/Show-Hide-Password/style.css
Labels: hacktoberfest2022, hacktoberfest

#13 Added solution of a python issue
  Python Programs/Eratosthenes.py
Labels: hacktoberfest2022, hacktoberfest

#6 Added a simple program of JS
  Included Images/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f666f726b2e706e67.png
  Javascript Programs/Fibonacci.js
Labels: hacktoberfest2022, hacktoberfest

#56 Update multiplication.java
  multiplication(java-program)/multiplication.java
Labels: good first issue, hacktoberfest2022, hacktoberfest

#53 Completed Quiz App
  Quiz App/index.html
  Quiz App/script.js
  Quiz App/style.css
Labels: good first issue, hacktoberfest2022, hacktoberfest

#68 commit done
  kilotomile/kilotomile.js
Labels: good first issue, hacktoberfest2022, hacktoberfest

#66 commit done
  swap/swaptonun.js
Labels: good first issue, hacktoberfest2022, hacktoberfest

#64 commit done
  findsqroot/sqroot.js
Labels: good first issue, hacktoberfest2022, hacktoberfest

#60 weather-app using HTML, CSS ,JavaScript
  weather app/index.html
  weather app/script.js
  weather app/style.css
Labels: good first issue, hacktoberfest2022, hacktoberfest

#82 Commit done
  .vscode/settings.json
  Login_page/app.js
  Login_page/index.html
  Login_page/style.css
Labels: good first issue, hacktoberfest2022, hacktoberfest

#78 Portfolio
  exception_handle.py
  naman.html
  rock_paper_scissors.py
  slicing.py
Labels: good first issue, hacktoberfest2022, hacktoberfest

#74 Done new task
  Landing Page/img/arrow-left.svg
  Landing Page/img/arrow-right.svg
  Landing Page/img/big-eclipse.svg
  Landing Page/img/cart.svg
  Landing Page/img/dot-full.svg
  Landing Page/img/dot.svg
  Landing Page/img/logo.svg
  Landing Page/img/matebook.png
  Landing Page/img/mid-eclipse.svg
  Landing Page/img/small-eclipse.svg
  Landing Page/index.html
  Landing Page/style.css
Labels: good first issue, hacktoberfest2022, hacktoberfest

#51 commit done
  multiplication(java-program)/multiplication.java
  restorent_website/index.html
  restorent_website/style.css
Labels: good first issue, hacktoberfest2022, hacktoberfest
